Numpy


In [1]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/8c/4a/556406d2bb2b9874c8cbc840c962683ac28f21efbc9b01177d78f0199ca1/numpy-2.3.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 162.5 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 163.8 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 163.4 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 202.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.0 MB 1.3 MB/s eta 0:00:11
   ---------------------------------------- 0.1/13.0 MB 1.3 MB/s eta 0:00:10
    ------------------------------


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np # import is keyword, as is alias, np is alias
print(np.__version__)

2.3.0


In [5]:
lst =list(range(1,25))
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [6]:
type(lst)

list

In [7]:
# array and list

# list is hetrogenous
# list is homogenous

# list  convert into array
arr =np.array(lst)


In [8]:
type(arr)

numpy.ndarray

In [11]:
arr =np.array([1,2,4,5,6,7,7,7,77,8,8,9,3])
arr

array([ 1,  2,  4,  5,  6,  7,  7,  7, 77,  8,  8,  9,  3])

In [14]:
arr =np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [17]:
arr =np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
arr =np.zeros((5,10))  ## 5 rows 10 columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
arr =np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
arr.reshape(10,3)  ## 3 column and 10 rows


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [27]:
arr=np.random.randint(1,5,9)
arr

array([2, 4, 1, 4, 2, 4, 3, 2, 4], dtype=int32)

In [28]:
arr=np.random.randint(1,5,(5,2))
arr

array([[3, 2],
       [2, 3],
       [4, 2],
       [3, 4],
       [1, 1]], dtype=int32)

In [29]:
arr =np.random.random(10)
arr

array([0.98839631, 0.41334388, 0.8356724 , 0.8650317 , 0.01921885,
       0.10373253, 0.43132916, 0.27061607, 0.21250429, 0.57322673])

In [30]:
np.random.random((5,10))

array([[0.10861096, 0.97455089, 0.86315862, 0.45465609, 0.05640035,
        0.57946079, 0.95184903, 0.99804067, 0.34738243, 0.39468463],
       [0.88905135, 0.35906322, 0.13462007, 0.71933755, 0.14561003,
        0.75692042, 0.66030996, 0.30932354, 0.50915178, 0.86108067],
       [0.82048922, 0.53161981, 0.20944902, 0.40954769, 0.676871  ,
        0.101743  , 0.73832306, 0.20132846, 0.97149477, 0.69365837],
       [0.79704234, 0.60827291, 0.49801404, 0.29877527, 0.05070259,
        0.86709615, 0.57568319, 0.60546026, 0.85047612, 0.23786443],
       [0.33489327, 0.53154821, 0.83862343, 0.50585093, 0.9261645 ,
        0.57424019, 0.80445644, 0.96727464, 0.25797556, 0.62735535]])

Array Attribute

In [38]:
arr=np.arange(60).reshape(12,5)   ## 12 rows and 5 columns
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
print("array shape:-",arr.shape )
print("array size:-",arr.size)
print("array datatype:- ",arr.dtype)
print("array ndim:- ",arr.ndim)  ## dimension of an array

array shape:- (12, 5)
array size:- 60
array datatype:-  int64
array ndim:-  2


In [ ]:
# 2D array into 1D array

arr = arr.flatten()
print("array shape:-",arr.shape )
print("array size:-",arr.size)
print("array datatype:- ",arr.dtype)
print("array ndim:- ",arr.ndim)  

array shape:- (60,)
array size:- 60
array datatype:-  int64
array ndim:-  1
